# Makefile for user's guide
# $Id: Makefile,v 1.1 2005/10/12 16:52:41 suravee Exp $

all:

XML_SRCS = \
	KTAU_Architecture.xml
ROOT = ../../

# the target, you will get $(TARGET).html $(TARGET).pdf, etc
TARGET =KTAU_Architecture

# (e.g. book.xml)
HEAD = KTAU_Architecture

include ../../Makefile.inc

