# Makefile for user's guide
# $Id: Makefile,v 1.1 2005/08/11 22:40:13 wspear Exp $

all:

XML_SRCS = TraceFileReaderHelp.xml
ROOT = ..

# the target, you will get $(TARGET).html $(TARGET).pdf, etc
TARGET = TraceFileReaderHelp

# (e.g. book.xml)
HEAD = TraceFileReaderHelp

include ../Makefile.inc
