# Makefile for user's guide
# $Id: Makefile,v 1.2 2005/09/23 00:04:22 amorris Exp $

XML_SRCS = \
	book.xml intro.xml management.xml thread.xml phase.xml function.xml 3d.xml comparison.xml misc.xml preferences.xml

ROOT = ..

# the target, you will get $(TARGET).html $(TARGET).pdf, etc
TARGET = paraprof

# (e.g. book.xml)
HEAD = book

include ../Makefile.inc
