# Makefile for user's guide
# $Id: Makefile,v 1.2 2012/12/04 06:35:14 khuck Exp $

XML_SRCS = \
	book.xml ch01.xml ch02.xml ch03.xml ch04.xml

ROOT = ..

# the target, you will get $(TARGET).html $(TARGET).pdf, etc
TARGET = perfdmf

# (e.g. book.xml)
HEAD = book

include ../Makefile.inc
