# Makefile for user's guide
# $Id: Makefile,v 1.1 2006/02/09 20:09:41 scottb Exp $

all:

XML_SRCS = \
	tools.xml 
ROOT = ..

# the target, you will get $(TARGET).html $(TARGET).pdf, etc
TARGET = tools

# (e.g. book.xml)
HEAD = tools

include ../Makefile.inc

