# Makefile for user's guide
# $Id: Makefile,v 1.1 2009/03/13 22:53:36 scottb Exp $

all:

XML_SRCS = \
	referenceguide.xml 
ROOT = ..

# the target, you will get $(TARGET).html $(TARGET).pdf, etc
TARGET = referenceguide

# (e.g. book.xml)
HEAD = referenceguide

include ../Makefile.inc

