# Makefile for user's guide
# $Id: Makefile,v 1.5 2005/06/29 17:24:08 scottb Exp $

all:

XML_SRCS = \
	book.xml 
ROOT = ..

# the target, you will get $(TARGET).html $(TARGET).pdf, etc
TARGET = userguide

# (e.g. book.xml)
HEAD = book

include ../Makefile.inc

