# Makefile for user's guide
# $Id: Makefile,v 1.1 2005/10/18 21:32:39 scottb Exp $

XML_SRCS = \
	taujava.xml
	
ROOT = ..

# the target, you will get $(TARGET).html $(TARGET).pdf, etc
TARGET = taujava

# (e.g. book.xml)
HEAD = taujava

include ../Makefile.inc
