# Makefile for user's guide
# $Id: Makefile,v 1.1 2005/07/12 18:17:46 wspear Exp $

all:

XML_SRCS = \
	tauutils.xml #TraceFileReaderHelp.xml
ROOT = ..

# the target, you will get $(TARGET).html $(TARGET).pdf, etc
TARGET = tauutils

# (e.g. book.xml)
HEAD = tauutils

include ../Makefile.inc

