# Makefile for user's guide
# $Id: Makefile,v 1.3 2005/08/17 17:47:26 khuck Exp $

XML_SRCS = \
	perfexplorer.xml	\
	ch01.xml	\
	ch02.xml	\
	ch03.xml	\
	ch04.xml	\
	ch05.xml	\
	ch06.xml	\
	ch07.xml	\
	ch08.xml	\
	ch09.xml	

ROOT = ..

# the target, you will get $(TARGET).html $(TARGET).pdf, etc
TARGET = perfexplorer

# (e.g. book.xml)
HEAD = perfexplorer

include ../Makefile.inc
