# Makefile for user's guide
# $Id: Makefile,v 1.2 2012/12/04 06:35:13 khuck Exp $

all:

XML_SRCS = \
	book.xml 
ROOT = ..

# the target, you will get $(TARGET).html $(TARGET).pdf, etc
TARGET = newguide

# (e.g. book.xml)
HEAD = book

include ../Makefile.inc

html-chunked: $(TARGET)-chunked
