# Makefile for user's guide
# $Id: Makefile,v 1.1 2005/10/12 17:01:41 suravee Exp $

all:

XML_SRCS = \
	KTAU_ZeptoOS_Installation.xml
ROOT = ../../

# the target, you will get $(TARGET).html $(TARGET).pdf, etc
TARGET =KTAU_ZeptoOS_Installation

# (e.g. book.xml)
HEAD = KTAU_ZeptoOS_Installation

include ../../Makefile.inc

