# Makefile for user's guide
# $Id: Makefile,v 1.1 2005/10/12 16:53:35 suravee Exp $

all:

XML_SRCS = \
	KTAU_ZeptoOS_Infrastructure.xml
ROOT = ../../

# the target, you will get $(TARGET).html $(TARGET).pdf, etc
TARGET =KTAU_ZeptoOS_Infrastructure

# (e.g. book.xml)
HEAD = KTAU_ZeptoOS_Infrastructure

include ../../Makefile.inc

