# Makefile for user's guide
# $Id: Makefile,v 1.1 2005/10/12 16:59:28 suravee Exp $

all:

XML_SRCS = \
	ktau.xml
ROOT = ..

# the target, you will get $(TARGET).html $(TARGET).pdf, etc
TARGET = ktau

# (e.g. book.xml)
HEAD = ktau

include ../Makefile.inc

