# Makefile for user's guide
# $Id: Makefile,v 1.1 2005/07/11 18:09:39 hoge Exp $

all:

XML_SRCS = \
	taucompiler.xml 
ROOT = ..

# the target, you will get $(TARGET).html $(TARGET).pdf, etc
TARGET = taucompiler

# (e.g. book.xml)
HEAD = taucompiler

include ../Makefile.inc

