# Makefile for user's guide
# $Id: Makefile,v 1.1 2005/11/10 19:20:12 scottb Exp $

all:

XML_SRCS = TraceFileWriter.xml
ROOT = ..

# the target, you will get $(TARGET).html $(TARGET).pdf, etc
TARGET = TraceFileWriter

# (e.g. book.xml)
HEAD = TraceFileWriter

include ../Makefile.inc
