# Makefile for user's guide
# $Id: Makefile,v 1.4 2005/08/15 16:05:59 amorris Exp $

all:

XML_SRCS = book.xml tauapis.xml taumapping.xml
ROOT = ..

# the target, you will get $(TARGET).html $(TARGET).pdf, etc
TARGET = tauapi

# (e.g. book.xml)
HEAD = book

include ../Makefile.inc
