# Makefile for user's guide
# $Id: Makefile,v 1.1 2009/11/12 04:10:02 scottb Exp $

all:

XML_SRCS = \
	 scenario.xml #TraceFileReaderHelp.xml
ROOT = ..

# the target, you will get $(TARGET).html $(TARGET).pdf, etc
TARGET = scenario

# (e.g. book.xml)
HEAD = scenario

include ../Makefile.inc

