# Makefile for TAU tutorial

all:

XML_SRCS = \
	tutorial.xml 
ROOT = ..

# the target, you will get $(TARGET).html $(TARGET).pdf, etc
TARGET = tutorial

# (e.g. book.xml)
HEAD = tutorial

include ../Makefile.inc
